; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "幽灵下载者"
#define MyAppVersion "APPLICATION_VERSION"
#define MyAppPublisher "XiaoYouChR"
#define MyAppURL "/"
#define MyAppExeName "Ghost-Downloader-3.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{C7E5C3F5-8579-4C76-BC5F-2D18D82FD9B8}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
SourceDir=..
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=LICENSE
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=dist
OutputBaseFilename=Ghost-Downloader-v{#MyAppVersion}-Windows-Setup
SetupIconFile=app/assets/installer_logo.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"
Name: "chinesetraditional"; MessagesFile: "compiler:Languages\ChineseTraditional.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "dist/Ghost-Downloader-3.dist/{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "dist/Ghost-Downloader-3.dist/*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Registry]
; Uninstall-time cleanup of the per-user assoc keys written at runtime; dontcreatekey writes nothing at install
Root: HKCU; Subkey: "Software\Classes\幽灵下载者.torrent"; Flags: dontcreatekey uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\幽灵下载者.m3u8"; Flags: dontcreatekey uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\幽灵下载者.m3u"; Flags: dontcreatekey uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\幽灵下载者.mpd"; Flags: dontcreatekey uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\.torrent\OpenWithProgids"; ValueType: none; ValueName: "幽灵下载者.torrent"; Flags: dontcreatekey uninsdeletevalue
Root: HKCU; Subkey: "Software\Classes\.m3u8\OpenWithProgids"; ValueType: none; ValueName: "幽灵下载者.m3u8"; Flags: dontcreatekey uninsdeletevalue
Root: HKCU; Subkey: "Software\Classes\.m3u\OpenWithProgids"; ValueType: none; ValueName: "幽灵下载者.m3u"; Flags: dontcreatekey uninsdeletevalue
Root: HKCU; Subkey: "Software\Classes\.mpd\OpenWithProgids"; ValueType: none; ValueName: "幽灵下载者.mpd"; Flags: dontcreatekey uninsdeletevalue
; URI scheme handlers registered at runtime
Root: HKCU; Subkey: "Software\Classes\ghostdownloader"; Flags: dontcreatekey uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\magnet"; Flags: dontcreatekey uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\ed2k"; Flags: dontcreatekey uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\ftp"; Flags: dontcreatekey uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\ftps"; Flags: dontcreatekey uninsdeletekey

[UninstallDelete]
Type: filesandordirs; Name: "{localappdata}\幽灵下载者"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
